name        : libgtkmm-3
version     : 3.18.0
release     : 7
source      :
    - http://ftp.acc.umu.se/pub/gnome/sources/gtkmm/3.18/gtkmm-3.18.0.tar.xz : 829fa113daed74398c49c3f2b7672807f58ba85d0fa463f5bc726e1b0138b86b
homepage    : http://www.gnome.org
license     : GPL-2.0
component   : desktop.gtk
summary     : C++ bindings to GTK+
description : |
    C++ bindings to GTK+
builddeps   :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(cairomm-1.0)
    - pkgconfig(pangomm-1.4)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - atkmm
    - devel:
        - atkmm-devel
patterns   :
    - devel: [/usr/lib64/g*]
    - docs: [/usr/share/devhelp, /usr/share/doc]
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
