name       : libgtkmm-3
version    : 3.24.5
release    : 18
source     :
    - https://download.gnome.org/sources/gtkmm/3.24/gtkmm-3.24.5.tar.xz : 856333de86689f6a81c123f2db15d85db9addc438bc3574c36f15736aeae22e6
license    : GPL-2.0-only
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangomm-1.4)
patterns   :
    - devel : [/usr/lib64/g*]
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
