name       : libgtkmm-3
version    : 3.24.2
release    : 16
source     :
    - https://download.gnome.org/sources/gtkmm/3.24/gtkmm-3.24.2.tar.xz : 6d71091bcd1863133460d4188d04102810e9123de19706fb656b7bb915b4adc3
license    : GPL-2.0-only
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(cairomm-1.0)
    - pkgconfig(pangomm-1.4)
rundeps    :
    - atkmm
    - devel :
        - atkmm-devel
patterns   :
    - devel : [/usr/lib64/g*]
    - docs : [/usr/share/devhelp, /usr/share/doc]
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
