name       : libgtkmm-3
version    : 3.22.2
release    : 11
source     :
    - https://download.gnome.org/sources/gtkmm/3.22/gtkmm-3.22.2.tar.xz : 91afd98a31519536f5f397c2d79696e3d53143b80b75778521ca7b48cb280090
homepage   : http://www.gnome.org
license    : GPL-2.0-only
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(cairomm-1.0)
    - pkgconfig(pangomm-1.4)
rundeps    :
    - atkmm
    - devel :
        - atkmm-devel
patterns   :
    - devel : [/usr/lib64/g*]
    - docs : [/usr/share/devhelp, /usr/share/doc]
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
