name       : libgtkmm-3
version    : 3.24.7
release    : 19
source     :
    - https://download.gnome.org/sources/gtkmm/3.24/gtkmm-3.24.7.tar.xz : 1d7a35af9c5ceccacb244ee3c2deb9b245720d8510ac5c7e6f4b6f9947e6789c
license    : GPL-2.0-only
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangomm-1.4)
patterns   :
    - devel : [/usr/lib64/g*]
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
