name       : libgtkmm-3
version    : 3.24.3
release    : 17
source     :
    - https://download.gnome.org/sources/gtkmm/3.24/gtkmm-3.24.3.tar.xz : 60497c4f7f354c3bd2557485f0254f8b7b4cf4bebc9fee0be26a77744eacd435
license    : GPL-2.0-only
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangomm-1.4)
patterns   :
    - devel : [/usr/lib64/g*]
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
