name       : libgtkmm-3
version    : 3.22.0
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gtkmm/3.22/gtkmm-3.22.0.tar.xz : 05da4d4b628fb20c8384630ddf478a3b5562952b2d6181fe28d58f6cbc0514f5
homepage   : http://www.gnome.org
license    : GPL-2.0
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(cairomm-1.0)
    - pkgconfig(pangomm-1.4)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - atkmm
    - devel :
        - atkmm-devel
patterns   :
    - devel : [/usr/lib64/g*]
    - docs : [/usr/share/devhelp, /usr/share/doc]
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
